# Generated by Django 5.2.8 on 2026-01-19 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('robo_id', models.CharField(help_text='Unique robot identifier', max_length=100, unique=True)),
                ('model_number', models.CharField(max_length=100)),
                ('local_ip', models.GenericIPAddressField(blank=True, help_text='Local network IP of the robot', null=True, protocol='IPv4')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('IN_TRANSIT', 'In Transit'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('emergency', models.BooleanField(default=False, help_text='Indicates emergency stop or critical state')),
                ('inspection_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('last_inspected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
