# Generated by Django 5.2.8 on 2026-01-19 10:20

import django.db.models.deletion
import robot_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_file', models.FileField(help_text='STCM map file for robot', upload_to='robot_maps/', validators=[robot_management.models.validate_stcm_file])),
                ('version', models.CharField(help_text='Map version or identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Currently active map')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='robot_management.robot')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'robot_maps',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_data', models.JSONField(help_text='Raw robot logs stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='robot_management.robot')),
            ],
            options={
                'db_table': 'robot_logs',
                'indexes': [models.Index(fields=['created_at'], name='robot_logs_created_23316f_idx')],
            },
        ),
    ]
