# Generated by Django 5.2.8 on 2026-01-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0002_robotmap_robotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
