# Generated by Django 5.2.8 on 2026-01-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0003_robot_is_deleted_alter_robot_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotmap',
            name='version',
        ),
    ]
