# Generated by Django 5.2.8 on 2026-01-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0004_remove_robotmap_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='robot_type',
            field=models.CharField(choices=[('INSPECTION', 'Inspection'), ('PICK_DROP', 'Pick and Drop')], default='INSPECTION', help_text='Type of robot (inspection or pick & drop)', max_length=20),
        ),
    ]
