# Generated by Django 5.2.8 on 2026-01-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0005_robot_robot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='is_deleted',
        ),
    ]
