# Generated by Django 5.2.8 on 2026-01-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0006_remove_robot_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='robot_management.robot')),
            ],
        ),
    ]
