# Generated by Django 5.2.8 on 2026-01-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0007_robotlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_mode', models.CharField(choices=[('autonomous', 'Autonomous'), ('stationary', 'Stationary')], max_length=20)),
                ('navigation_style', models.CharField(blank=True, choices=[('free', 'Free'), ('stick', 'Stick'), ('stick_with_autonomous', 'Stick With Autonomous')], max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to='robot_management.robot')),
            ],
        ),
    ]
