# Generated by Django 5.2.8 on 2026-01-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0008_robotnavigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='speak_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robotnavigation',
            name='navigation_style',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('strict', 'Strict'), ('strict_with_autonomous', 'Strict With Autonomous')], max_length=30, null=True),
        ),
    ]
