# Generated by Django 5.2.8 on 2026-01-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0009_robot_speak_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrateHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_hand_active', models.BooleanField(default=False)),
                ('right_hand_active', models.BooleanField(default=False)),
                ('left_point_one', models.JSONField(blank=True, null=True)),
                ('left_point_two', models.JSONField(blank=True, null=True)),
                ('left_point_three', models.JSONField(blank=True, null=True)),
                ('right_point_one', models.JSONField(blank=True, null=True)),
                ('right_point_two', models.JSONField(blank=True, null=True)),
                ('right_point_three', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrate_hands', to='robot_management.robot')),
            ],
        ),
    ]
