# Generated by Django 5.2.8 on 2026-01-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0010_calibratehand'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibratehand',
            name='left_point_one_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='left_point_three_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='left_point_two_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='right_point_one_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='right_point_three_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='right_point_two_active',
            field=models.BooleanField(default=False),
        ),
    ]
