# Generated by Django 5.2.8 on 2026-01-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0011_calibratehand_left_point_one_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibratehand',
            name='calibration_status',
            field=models.BooleanField(default=False),
        ),
    ]
