# Generated by Django 5.2.8 on 2026-01-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0012_calibratehand_calibration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibratehand',
            name='robot',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='robot_management.robot')),
            ],
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='robot_management.profile'),
        ),
    ]
