# Generated by Django 5.2.8 on 2026-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0014_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibratehand',
            name='left_hand_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='left_hand_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='left_hand_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='right_hand_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='right_hand_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibratehand',
            name='right_hand_update',
            field=models.BooleanField(default=False),
        ),
    ]
