# Generated by Django 5.2.8 on 2026-02-02 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0015_calibratehand_left_hand_retry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this robot', related_name='robots', to=settings.AUTH_USER_MODEL),
        ),
    ]
