# Generated by Django 5.2.8 on 2026-02-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0016_robot_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='users',
        ),
    ]
