# Generated by Django 5.2.8 on 2026-02-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0017_remove_robot_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='minimum_battery_charge',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum battery percentage required to start a schedule', null=True),
        ),
    ]
