# Generated by Django 5.2.8 on 2026-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0018_robot_minimum_battery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotnavigation',
            name='autonomous_ready',
            field=models.BooleanField(default=False),
        ),
    ]
