# Generated by Django 5.2.8 on 2026-02-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0019_robotnavigation_autonomous_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotnavigation',
            name='mode_active',
            field=models.BooleanField(default=False),
        ),
    ]
