# Generated by Django 5.2.8 on 2026-02-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0020_robotnavigation_mode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='operation_mode',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
