# Generated by Django 5.2.8 on 2026-02-02 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_reset_token_and_more'),
        ('robot_management', '0017_remove_robot_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_assignments_done', to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='robot_management.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_robots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('robot', 'user')},
            },
        ),
    ]
