# Generated by Django 5.2.8 on 2026-02-02 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_robotuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotuser',
            options={'verbose_name': 'Robot User Assignment', 'verbose_name_plural': 'Robot User Assignments'},
        ),
        migrations.AlterField(
            model_name='robotuser',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_assignments_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
