# Generated by Django 5.2.8 on 2026-01-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robot_management', '0006_remove_robot_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RimType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emergency_stop', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_stop', to='robot_management.robot')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='robot_management.robot')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rim_id', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rim_photos/')),
                ('is_defect', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('is_human_verified', models.BooleanField(default=False)),
                ('false_detected', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('correct_label', models.CharField(blank=True, max_length=100, null=True)),
                ('rim_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inseption.rimtype')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inseption.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'rim_id')},
            },
        ),
    ]
