# Generated by Django 5.2.8 on 2026-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
