# Generated by Django 5.2.8 on 2025-11-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rim_id', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rim_photos/')),
                ('is_defect', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RimInspection',
        ),
        migrations.AddField(
            model_name='inspection',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inseption.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together={('schedule', 'rim_id')},
        ),
    ]
