# Generated by Django 5.2.8 on 2025-11-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0002_inspection_schedule_delete_riminspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
