# Generated by Django 5.2.8 on 2025-11-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0003_schedule_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='rim_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
