# Generated by Django 5.2.8 on 2025-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0004_alter_inspection_rim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
