# Generated by Django 5.2.8 on 2025-11-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0005_inspection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict)),
            ],
        ),
    ]
