# Generated by Django 5.2.8 on 2026-01-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0006_speakconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='correct_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='false_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_human_verified',
            field=models.BooleanField(default=False),
        ),
    ]
