# Generated by Django 5.2.8 on 2026-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0008_rimtype_inspection_rim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
