# Generated by Django 5.2.8 on 2026-01-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0009_inspection_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emergency_stop', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
