# Generated by Django 5.2.8 on 2026-01-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0010_emergencystop'),
        ('robot_management', '0006_remove_robot_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencystop',
            name='robot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_stop', to='robot_management.robot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='robot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='robot_management.robot'),
        ),
    ]
