# Generated by Django 5.2.8 on 2026-01-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseption', '0012_alter_schedule_robot'),
        ('robot_management', '0006_remove_robot_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='robot_management.robot'),
        ),
    ]
